// Mocks generated by Mockito 5.4.5 from annotations
// in m360_app_corpsec/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i6;
import 'package:m360_app_corpsec/models/model.account.dart' as _i2;
import 'package:m360_app_corpsec/models/model.company.dart' as _i12;
import 'package:m360_app_corpsec/models/model.customer.dart' as _i14;
import 'package:m360_app_corpsec/models/model.salesInvoice.dart' as _i3;
import 'package:m360_app_corpsec/services/authentication_service.dart' as _i9;
import 'package:m360_app_corpsec/services/business_central_service.dart'
    as _i13;
import 'package:m360_app_corpsec/services/company_service.dart' as _i11;
import 'package:m360_app_corpsec/services/share_service.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:stacked_services/stacked_services.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTokenSet_0 extends _i1.SmartFake implements _i2.TokenSet {
  _FakeTokenSet_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSalesInvoice_1 extends _i1.SmartFake implements _i3.SalesInvoice {
  _FakeSalesInvoice_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i4.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
      ) as String);

  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
      ) as String);

  @override
  _i6.GlobalKey<_i6.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i6.GlobalKey<_i6.NavigatorState>?);

  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i4.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<T?>? navigateWithTransition<T>(
    _i6.Widget? page, {
    bool? opaque,
    String? transition = '',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i6.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i4.Transition? transitionClass,
    _i4.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? replaceWithTransition<T>(
    _i6.Widget? page, {
    bool? opaque,
    String? transition = '',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i6.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i4.Transition? transitionClass,
    _i4.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void popUntil(
    _i6.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i6.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? navigateToView<T>(
    _i6.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i6.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i4.Transition? transition,
    _i4.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i6.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? clearStackAndShowView<T>(
    _i6.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? clearTillFirstAndShowView<T>(
    _i6.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i6.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i4.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i4.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i4.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = 'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
    double? elevation = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
            #elevation: elevation,
          },
        ),
        returnValue: _i7.Future<_i4.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i7.Future<_i4.SheetResponse<dynamic>?>.value(),
      ) as _i7.Future<_i4.SheetResponse<dynamic>?>);

  @override
  _i7.Future<_i4.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i8.Color? barrierColor = const _i8.Color(2315255808),
    double? elevation = 1.0,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = '',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #elevation: elevation,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i7.Future<_i4.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i7.Future<_i4.SheetResponse<T>?>.value(),
      ) as _i7.Future<_i4.SheetResponse<T>?>);

  @override
  void completeSheet(_i4.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i4.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i4.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i6.Widget Function(
      _i6.BuildContext,
      _i4.DialogRequest<dynamic>,
      dynamic Function(_i4.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i4.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i8.Color? cancelTitleColor,
    String? buttonTitle = 'Ok',
    _i8.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i6.RouteSettings? routeSettings,
    _i6.GlobalKey<_i6.NavigatorState>? navigatorKey,
    _i4.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i7.Future<_i4.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i7.Future<_i4.DialogResponse<dynamic>?>.value(),
      ) as _i7.Future<_i4.DialogResponse<dynamic>?>);

  @override
  _i7.Future<_i4.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i8.Color? barrierColor = const _i8.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = '',
    bool? useSafeArea = true,
    _i6.RouteSettings? routeSettings,
    _i6.GlobalKey<_i6.NavigatorState>? navigatorKey,
    _i6.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #transitionBuilder: transitionBuilder,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i7.Future<_i4.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i7.Future<_i4.DialogResponse<T>?>.value(),
      ) as _i7.Future<_i4.DialogResponse<T>?>);

  @override
  _i7.Future<_i4.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = 'Cancel',
    _i8.Color? cancelTitleColor,
    String? confirmationTitle = 'Ok',
    _i8.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i6.RouteSettings? routeSettings,
    _i4.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i7.Future<_i4.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i7.Future<_i4.DialogResponse<dynamic>?>.value(),
      ) as _i7.Future<_i4.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i4.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationService extends _i1.Mock
    implements _i9.AuthenticationService {
  @override
  set user(_i2.Account? _user) => super.noSuchMethod(
        Invocation.setter(
          #user,
          _user,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get discoveryUrl => (super.noSuchMethod(
        Invocation.getter(#discoveryUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#discoveryUrl),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#discoveryUrl),
        ),
      ) as String);

  @override
  String get clientId => (super.noSuchMethod(
        Invocation.getter(#clientId),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#clientId),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#clientId),
        ),
      ) as String);

  @override
  String get clientSecret => (super.noSuchMethod(
        Invocation.getter(#clientSecret),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#clientSecret),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#clientSecret),
        ),
      ) as String);

  @override
  String get redirectUrl => (super.noSuchMethod(
        Invocation.getter(#redirectUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#redirectUrl),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#redirectUrl),
        ),
      ) as String);

  @override
  String get scope => (super.noSuchMethod(
        Invocation.getter(#scope),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#scope),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#scope),
        ),
      ) as String);

  @override
  String get postLogoutRedirectUrl => (super.noSuchMethod(
        Invocation.getter(#postLogoutRedirectUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#postLogoutRedirectUrl),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#postLogoutRedirectUrl),
        ),
      ) as String);

  @override
  set openIdConfig(_i9.OpenIdConfig? _openIdConfig) => super.noSuchMethod(
        Invocation.setter(
          #openIdConfig,
          _openIdConfig,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isLocalAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isLocalAuthenticated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isBusy => (super.noSuchMethod(
        Invocation.getter(#isBusy),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isBusy(bool? _isBusy) => super.noSuchMethod(
        Invocation.setter(
          #isBusy,
          _isBusy,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool isLogin() => (super.noSuchMethod(
        Invocation.method(
          #isLogin,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<_i2.TokenSet?> getLoginViaStore() => (super.noSuchMethod(
        Invocation.method(
          #getLoginViaStore,
          [],
        ),
        returnValue: _i7.Future<_i2.TokenSet?>.value(),
        returnValueForMissingStub: _i7.Future<_i2.TokenSet?>.value(),
      ) as _i7.Future<_i2.TokenSet?>);

  @override
  _i7.Future<void> loginViaOidc() => (super.noSuchMethod(
        Invocation.method(
          #loginViaOidc,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.TokenSet> returnToAuthCodeLoginFlow(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #returnToAuthCodeLoginFlow,
          [code],
        ),
        returnValue: _i7.Future<_i2.TokenSet>.value(_FakeTokenSet_0(
          this,
          Invocation.method(
            #returnToAuthCodeLoginFlow,
            [code],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.TokenSet>.value(_FakeTokenSet_0(
          this,
          Invocation.method(
            #returnToAuthCodeLoginFlow,
            [code],
          ),
        )),
      ) as _i7.Future<_i2.TokenSet>);

  @override
  _i7.Future<_i2.TokenSet> getOidcTokenWithRefreshToken() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOidcTokenWithRefreshToken,
          [],
        ),
        returnValue: _i7.Future<_i2.TokenSet>.value(_FakeTokenSet_0(
          this,
          Invocation.method(
            #getOidcTokenWithRefreshToken,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.TokenSet>.value(_FakeTokenSet_0(
          this,
          Invocation.method(
            #getOidcTokenWithRefreshToken,
            [],
          ),
        )),
      ) as _i7.Future<_i2.TokenSet>);

  @override
  _i7.Future<_i2.TokenSet> loginCentralWithOidcToken(_i2.TokenSet? tr) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginCentralWithOidcToken,
          [tr],
        ),
        returnValue: _i7.Future<_i2.TokenSet>.value(_FakeTokenSet_0(
          this,
          Invocation.method(
            #loginCentralWithOidcToken,
            [tr],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.TokenSet>.value(_FakeTokenSet_0(
          this,
          Invocation.method(
            #loginCentralWithOidcToken,
            [tr],
          ),
        )),
      ) as _i7.Future<_i2.TokenSet>);

  @override
  _i7.Future<void> loginViaEmail(Map<dynamic, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginViaEmail,
          [data],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.TokenSet> loginViaRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #loginViaRefreshToken,
          [],
        ),
        returnValue: _i7.Future<_i2.TokenSet>.value(_FakeTokenSet_0(
          this,
          Invocation.method(
            #loginViaRefreshToken,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.TokenSet>.value(_FakeTokenSet_0(
          this,
          Invocation.method(
            #loginViaRefreshToken,
            [],
          ),
        )),
      ) as _i7.Future<_i2.TokenSet>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logoutOidc() => (super.noSuchMethod(
        Invocation.method(
          #logoutOidc,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> registerDeviceToken(String? deviceToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerDeviceToken,
          [deviceToken],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> afterLogin(_i2.TokenSet? ts) => (super.noSuchMethod(
        Invocation.method(
          #afterLogin,
          [ts],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> biometricAuthAction({String? reason = ' '}) =>
      (super.noSuchMethod(
        Invocation.method(
          #biometricAuthAction,
          [],
          {#reason: reason},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setUseBiometricAction(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setUseBiometricAction,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void setBusy(bool? flag) => super.noSuchMethod(
        Invocation.method(
          #setBusy,
          [flag],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ShareService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareService extends _i1.Mock implements _i10.ShareService {
  @override
  set onFunc(_i8.VoidCallback? _onFunc) => super.noSuchMethod(
        Invocation.setter(
          #onFunc,
          _onFunc,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get postCount => (super.noSuchMethod(
        Invocation.getter(#postCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void callChild() => super.noSuchMethod(
        Invocation.method(
          #callChild,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void callParent() => super.noSuchMethod(
        Invocation.method(
          #callParent,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePostCount() => super.noSuchMethod(
        Invocation.method(
          #updatePostCount,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetCount() => super.noSuchMethod(
        Invocation.method(
          #resetCount,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CompanyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompanyService extends _i1.Mock implements _i11.CompanyService {
  @override
  set currentCompany(_i12.Company? _currentCompany) => super.noSuchMethod(
        Invocation.setter(
          #currentCompany,
          _currentCompany,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i12.Company> get companyArr => (super.noSuchMethod(
        Invocation.getter(#companyArr),
        returnValue: <_i12.Company>[],
        returnValueForMissingStub: <_i12.Company>[],
      ) as List<_i12.Company>);

  @override
  set companyArr(List<_i12.Company>? _companyArr) => super.noSuchMethod(
        Invocation.setter(
          #companyArr,
          _companyArr,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isBusy => (super.noSuchMethod(
        Invocation.getter(#isBusy),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isBusy(bool? _isBusy) => super.noSuchMethod(
        Invocation.setter(
          #isBusy,
          _isBusy,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i7.Future<void> setCurrentCompany({
    String? companyId,
    _i12.Company? company,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCurrentCompany,
          [],
          {
            #companyId: companyId,
            #company: company,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i12.Company?> getCompany(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCompany,
          [id],
        ),
        returnValue: _i7.Future<_i12.Company?>.value(),
        returnValueForMissingStub: _i7.Future<_i12.Company?>.value(),
      ) as _i7.Future<_i12.Company?>);

  @override
  _i7.Future<List<_i12.Company>> getAllCompany() => (super.noSuchMethod(
        Invocation.method(
          #getAllCompany,
          [],
        ),
        returnValue: _i7.Future<List<_i12.Company>>.value(<_i12.Company>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i12.Company>>.value(<_i12.Company>[]),
      ) as _i7.Future<List<_i12.Company>>);

  @override
  _i7.Future<List<_i12.Timeline>> getDashboardTimeline(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDashboardTimeline,
          [id],
        ),
        returnValue: _i7.Future<List<_i12.Timeline>>.value(<_i12.Timeline>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i12.Timeline>>.value(<_i12.Timeline>[]),
      ) as _i7.Future<List<_i12.Timeline>>);

  @override
  _i7.Future<List<_i12.Document>> getDocuments(String? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocuments,
          [companyId],
        ),
        returnValue: _i7.Future<List<_i12.Document>>.value(<_i12.Document>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i12.Document>>.value(<_i12.Document>[]),
      ) as _i7.Future<List<_i12.Document>>);

  @override
  String getPreviewCompanyDocumentUrl(
    String? key,
    String? sessionAccessToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPreviewCompanyDocumentUrl,
          [
            key,
            sessionAccessToken,
          ],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getPreviewCompanyDocumentUrl,
            [
              key,
              sessionAccessToken,
            ],
          ),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getPreviewCompanyDocumentUrl,
            [
              key,
              sessionAccessToken,
            ],
          ),
        ),
      ) as String);

  @override
  void setBusy(bool? flag) => super.noSuchMethod(
        Invocation.method(
          #setBusy,
          [flag],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BusinessCentralService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBusinessCentralService extends _i1.Mock
    implements _i13.BusinessCentralService {
  @override
  List<_i14.Customer> get customerArr => (super.noSuchMethod(
        Invocation.getter(#customerArr),
        returnValue: <_i14.Customer>[],
        returnValueForMissingStub: <_i14.Customer>[],
      ) as List<_i14.Customer>);

  @override
  set customerArr(List<_i14.Customer>? _customerArr) => super.noSuchMethod(
        Invocation.setter(
          #customerArr,
          _customerArr,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i3.SalesInvoice> get salesInvoiceArr => (super.noSuchMethod(
        Invocation.getter(#salesInvoiceArr),
        returnValue: <_i3.SalesInvoice>[],
        returnValueForMissingStub: <_i3.SalesInvoice>[],
      ) as List<_i3.SalesInvoice>);

  @override
  set salesInvoiceArr(List<_i3.SalesInvoice>? _salesInvoiceArr) =>
      super.noSuchMethod(
        Invocation.setter(
          #salesInvoiceArr,
          _salesInvoiceArr,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isBusy => (super.noSuchMethod(
        Invocation.getter(#isBusy),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isBusy(bool? _isBusy) => super.noSuchMethod(
        Invocation.setter(
          #isBusy,
          _isBusy,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i7.Future<List<_i14.Customer>> getAllCustomers() => (super.noSuchMethod(
        Invocation.method(
          #getAllCustomers,
          [],
        ),
        returnValue: _i7.Future<List<_i14.Customer>>.value(<_i14.Customer>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i14.Customer>>.value(<_i14.Customer>[]),
      ) as _i7.Future<List<_i14.Customer>>);

  @override
  _i7.Future<List<_i3.SalesInvoice>> getAllPostedSalesInvoice() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPostedSalesInvoice,
          [],
        ),
        returnValue:
            _i7.Future<List<_i3.SalesInvoice>>.value(<_i3.SalesInvoice>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i3.SalesInvoice>>.value(<_i3.SalesInvoice>[]),
      ) as _i7.Future<List<_i3.SalesInvoice>>);

  @override
  _i7.Future<_i3.SalesInvoice> getSalesInvoiceDetail(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSalesInvoiceDetail,
          [id],
        ),
        returnValue: _i7.Future<_i3.SalesInvoice>.value(_FakeSalesInvoice_1(
          this,
          Invocation.method(
            #getSalesInvoiceDetail,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.SalesInvoice>.value(_FakeSalesInvoice_1(
          this,
          Invocation.method(
            #getSalesInvoiceDetail,
            [id],
          ),
        )),
      ) as _i7.Future<_i3.SalesInvoice>);

  @override
  void setBusy(bool? flag) => super.noSuchMethod(
        Invocation.method(
          #setBusy,
          [flag],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
